create table "public"."banner" (
    "id" bigint generated by default as identity not null,
    "uuid" uuid not null default gen_random_uuid(),
    "image" text not null,
    "url" text not null
);


CREATE UNIQUE INDEX banner_pkey ON public.banner USING btree (id);

CREATE UNIQUE INDEX banner_uuid_key ON public.banner USING btree (uuid);

alter table "public"."banner" add constraint "banner_pkey" PRIMARY KEY using index "banner_pkey";

alter table "public"."banner" add constraint "banner_uuid_key" UNIQUE using index "banner_uuid_key";

grant delete on table "public"."banner" to "anon";

grant insert on table "public"."banner" to "anon";

grant references on table "public"."banner" to "anon";

grant select on table "public"."banner" to "anon";

grant trigger on table "public"."banner" to "anon";

grant truncate on table "public"."banner" to "anon";

grant update on table "public"."banner" to "anon";

grant delete on table "public"."banner" to "authenticated";

grant insert on table "public"."banner" to "authenticated";

grant references on table "public"."banner" to "authenticated";

grant select on table "public"."banner" to "authenticated";

grant trigger on table "public"."banner" to "authenticated";

grant truncate on table "public"."banner" to "authenticated";

grant update on table "public"."banner" to "authenticated";

grant delete on table "public"."banner" to "service_role";

grant insert on table "public"."banner" to "service_role";

grant references on table "public"."banner" to "service_role";

grant select on table "public"."banner" to "service_role";

grant trigger on table "public"."banner" to "service_role";

grant truncate on table "public"."banner" to "service_role";

grant update on table "public"."banner" to "service_role";


