-- Create answer_sheets table
CREATE TABLE public.answer_sheets (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "uuid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "book_id" uuid NOT NULL,
  "counts" integer NOT NULL CHECK (counts > 0),
  "answers" integer [] NOT NULL CHECK (array_position(answers, NULL) IS NULL AND array_length(answers, 1) = counts),
  "points" integer [] NOT NULL CHECK (array_position(answers, NULL) IS NULL AND array_length(answers, 1) = counts),
  "n_options" integer [] NOT NULL CHECK (array_position(answers, NULL) IS NULL AND array_length(answers, 1) = counts),
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Add primary key and unique constraints
ALTER TABLE
  public.answer_sheets
ADD
  CONSTRAINT answer_sheets_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX answer_sheets_uuid_key ON public.answer_sheets USING btree (uuid);

ALTER TABLE
  public.answer_sheets
ADD
  CONSTRAINT answer_sheets_uuid_key UNIQUE USING INDEX answer_sheets_uuid_key;

-- Add foreign key constraint
ALTER TABLE
  public.answer_sheets
ADD
  CONSTRAINT answer_sheets_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.books(uuid) ON UPDATE CASCADE ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE
  public.answer_sheets ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Allow authenticated read access on answer_sheets" ON public.answer_sheets FOR
SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert on answer_sheets" ON public.answer_sheets FOR
INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update on answer_sheets" ON public.answer_sheets FOR
UPDATE
  USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated delete on answer_sheets" ON public.answer_sheets FOR DELETE USING (auth.role() = 'authenticated');

-- Grant permissions to authenticated users
GRANT
  SELECT, INSERT, UPDATE, DELETE
ON
  TABLE public.answer_sheets TO authenticated;

-- Create trigger for updated_at
CREATE TRIGGER handle_answer_sheets_updated_at BEFORE
UPDATE
  ON public.answer_sheets FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');